services:
  - type: web
    name: anonbot-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production

  - type: web
    name: anonbot-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
