services:
  - type: web
    name: whatsapp-frontend-ui
    env: python
    buildCommand: pip install -r web/requirements.txt
    startCommand: python3 web/app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
    buildFilter:
      paths:
        - web/**/*
        
  - type: web
    name: anonbot-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    autoDeploy: true
